# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples

on:
  push:
    branches: [main, devel]
  pull_request:

name: jarl-check.yaml

permissions: read-all

jobs:
  jarl-check:
    name: jarl-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: etiennebacher/setup-jarl@v0.1.0

      - name: Check
        run: jarl check --fix
